# Generated by Django 5.2.8 on 2025-11-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('instrucciones', models.TextField()),
                ('imagen', models.ImageField(upload_to='recetas/')),
            ],
        ),
    ]
